show_downloads: false
theme: jekyll-theme-minimal
title: Wenjie Ji
description: Associate Professor, Westlake University
            <br>
            <a href="https://scholar.google.com/citations?user=bVjt0QwAAAAJ&hl=en"><i class="fa fa-graduation-cap"></i> Google Scholar</a>
